# Generated by Django 4.2.16 on 2026-01-26 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('APARTAMENTO', 'Apartamento'), ('CASA', 'Casa'), ('LOCAL', 'Local comercial'), ('OFICINA', 'Oficina'), ('LOTE', 'Lote'), ('BODEGA', 'Bodega')], max_length=20)),
                ('operacion', models.CharField(choices=[('VENTA', 'Venta'), ('ARRIENDO', 'Arriendo'), ('VENTA_ARRIENDO', 'Venta y Arriendo')], default='VENTA', max_length=15)),
                ('estado', models.CharField(choices=[('NUEVO', 'Nuevo'), ('USADO', 'Usado'), ('EN_CONSTRUCCION', 'En construcción')], default='USADO', max_length=20)),
                ('pais', models.CharField(default='Colombia', max_length=60)),
                ('departamento', models.CharField(max_length=60)),
                ('ciudad', models.CharField(max_length=60)),
                ('barrio', models.CharField(max_length=80)),
                ('direccion', models.CharField(blank=True, max_length=150)),
                ('area_m2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('area_construida_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('habitaciones', models.IntegerField(default=0)),
                ('banos', models.IntegerField(default=0)),
                ('parqueaderos', models.IntegerField(default=0)),
                ('estrato', models.IntegerField(blank=True, null=True)),
                ('piso', models.IntegerField(blank=True, null=True)),
                ('ano_construccion', models.IntegerField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=14)),
                ('administracion', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('moneda', models.CharField(default='COP', max_length=10)),
                ('estatus', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('RESERVADO', 'Reservado'), ('VENDIDO', 'Vendido'), ('ARRENDADO', 'Arrendado'), ('INACTIVO', 'Inactivo')], default='DISPONIBLE', max_length=12)),
                ('destacado', models.BooleanField(default=False)),
                ('nombre_contacto', models.CharField(blank=True, max_length=100)),
                ('telefono_contacto', models.CharField(blank=True, max_length=30)),
                ('email_contacto', models.EmailField(blank=True, max_length=254)),
                ('fecha_publicacion', models.DateField()),
                ('fecha_actualizacion', models.DateField()),
            ],
            options={
                'verbose_name': 'Inmueble',
                'verbose_name_plural': 'Inmuebles',
                'db_table': 'inmuebles',
            },
        ),
    ]
