# Generated by Django 4.2.16 on 2026-04-20 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='imagen1',
            field=models.ImageField(blank=True, null=True, upload_to='inmuebles/'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='inmuebles/'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='imagen3',
            field=models.ImageField(blank=True, null=True, upload_to='inmuebles/'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='imagen4',
            field=models.ImageField(blank=True, null=True, upload_to='inmuebles/'),
        ),
    ]
