# Generated by Django 4.2.16 on 2026-04-20 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inmuebles', '0002_inmueble_imagen1_inmueble_imagen2_inmueble_imagen3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
