# Generated by Django 4.2.16 on 2026-04-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0003_inmueble_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='fecha_actualizacion',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='fecha_publicacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
