# Generated by Django 5.2.17 on 2026-10-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0004_alter_inmueble_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='operacion',
            field=models.CharField(choices=[('VENTA', 'Venta'), ('ARRIENDO', 'Arriendo'), ('CESION', 'Cesión')], default='VENTA', max_length=15),
        ),
    ]
