# Generated by Django 5.2.17 on 2026-10-04 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0005_alter_inmueble_operacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='meses_entrega',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='modalidad_entrega',
            field=models.CharField(choices=[('TERMINADO', 'Terminada / entrega inmediata'), ('SOBRE_PLANOS', 'Sobre planos')], default='TERMINADO', max_length=15),
        ),
    ]
