# Generated by Django 5.2.17 on 2026-10-04 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0007_en_construccion_sobre_planos'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='empresa',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='fecha_entrega_constructora',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='porcentaje_inicial_exigido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='valor_separacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
