# Generated by Django 5.2.17 on 2026-10-03 14:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inmuebles', '0005_alter_inmueble_operacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenciaFinanciera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.CharField(max_length=120)),
                ('producto', models.CharField(max_length=120)),
                ('tasa_ea', models.DecimalField(decimal_places=5, max_digits=7)),
                ('fuente', models.URLField(blank=True)),
                ('condiciones', models.TextField(blank=True)),
                ('verificada', models.DateField()),
                ('vence', models.DateField()),
                ('plazo_minimo', models.PositiveSmallIntegerField(default=5)),
                ('plazo_maximo', models.PositiveSmallIntegerField(default=20)),
                ('porcentaje_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('activa', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Perfilacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clave_sesion', models.CharField(db_index=True, max_length=40)),
                ('respuestas', models.JSONField(default=dict)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('version_preguntas', models.CharField(default='1', max_length=12)),
                ('estado', models.CharField(choices=[('EXPLORACION', 'Exploración'), ('PRELIMINAR', 'Resultado preliminar'), ('SOLICITUD', 'Solicitud registrada')], default='EXPLORACION', max_length=24)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluacionPerfil',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField()),
                ('respuestas', models.JSONField()),
                ('resultados', models.JSONField()),
                ('version_reglas', models.CharField(default='1', max_length=12)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('perfilacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='perfilador.perfilacion')),
            ],
        ),
        migrations.CreateModel(
            name='SimulacionFinanciera',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField()),
                ('parametros', models.JSONField()),
                ('resultado', models.JSONField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='perfilador.evaluacionperfil')),
                ('inmueble', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inmuebles.inmueble')),
                ('perfilacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulaciones', to='perfilador.perfilacion')),
                ('referencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='perfilador.referenciafinanciera')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudAsesoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('telefono', models.CharField(blank=True, max_length=40)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('preferencia_contacto', models.CharField(choices=[('TELEFONO', 'Teléfono'), ('CORREO', 'Correo')], max_length=12)),
                ('accion', models.CharField(choices=[('VISITA', 'Visita'), ('FINANCIACION', 'Revisar financiación'), ('CONDICIONES', 'Confirmar condiciones'), ('ACOMPANAMIENTO', 'Acompañamiento')], max_length=24)),
                ('consentimiento', models.BooleanField(default=False)),
                ('clave_idempotencia', models.UUIDField()),
                ('estado', models.CharField(default='NUEVA', max_length=15)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='perfilador.evaluacionperfil')),
                ('inmueble', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inmuebles.inmueble')),
                ('perfilacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='perfilador.perfilacion')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('perfilacion', 'clave_idempotencia'), name='solicitud_unica_por_intento')],
            },
        ),
    ]
