# Generated by Django 5.2.17 on 2026-10-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfilador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilacion',
            name='version_preguntas',
            field=models.CharField(default='2', max_length=12),
        ),
        migrations.CreateModel(
            name='ReferenciaCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cop_por_usd', models.DecimalField(decimal_places=4, max_digits=14)),
                ('fecha', models.DateField(db_index=True)),
                ('fuente', models.URLField()),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('fecha', 'fuente'), name='cambio_unico_por_fuente_fecha')],
            },
        ),
    ]
