# Generated by Django 5.2.17 on 2026-10-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfilador', '0002_alter_perfilacion_version_preguntas_referenciacambio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilacion',
            name='version_preguntas',
            field=models.CharField(default='3', max_length=12),
        ),
    ]
