# Generated by Django 5.2.17 on 2026-10-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfilador', '0003_alter_perfilacion_version_preguntas'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='solicitudasesoria',
            name='solicitud_unica_por_intento',
        ),
        migrations.AlterField(
            model_name='perfilacion',
            name='version_preguntas',
            field=models.CharField(default='4', max_length=12),
        ),
        migrations.AlterField(
            model_name='solicitudasesoria',
            name='clave_idempotencia',
            field=models.UUIDField(unique=True),
        ),
    ]
