# Generated by Django 5.2.17 on 2026-10-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfilador', '0004_remove_solicitudasesoria_solicitud_unica_por_intento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilacion',
            name='version_preguntas',
            field=models.CharField(default='5', max_length=12),
        ),
    ]
