# Generated by Django 5.2.17 on 2026-10-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfilador', '0005_alter_perfilacion_version_preguntas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilacion',
            name='version_preguntas',
            field=models.CharField(default='6', max_length=12),
        ),
    ]
